# Generated by Django 4.2.1 on 2023-05-22 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='enail',
            new_name='email',
        ),
    ]
